version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-frontend:
    executor: node/default
    working_directory: ~/project/iam-enterprise-architecture-frontend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
      - run:
          command: npm install --save-dev @types/node
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public.output.next.docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: frontend-build
          
  build-backend:
    executor: node/default
    working_directory: ~/project/iam-enterprise-architecture-backend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public.output.next.docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: backend-build
      # Example usage of environment variables
      # - run:
      #     name: Use environment variables
      #     command: echo $MSAL_CLIENT_ID

  test-backend:
    executor: node/default
    working_directory: ~/project/iam-enterprise-architecture-backend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
      # Example usage of environment variables
      # - run:
      #     name: Use environment variables
      #     command: echo $MSAL_CLIENT_ID

  sonarqube-analysis:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run SonarQube Analysis
          command: |
            echo "Running SonarQube analysis..."
            if [[ $CIRCLE_TAG =~ ^prod|preprod$ ]]; then
              bash sonar_run.sh
            fi
      # Example usage of environment variables
      # - run:
      #     name: Use environment variables
      #     command: echo $MSAL_CLIENT_ID

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: |
            if [[ "$CIRCLE_BRANCH" == "main" ]]; then
              echo 'Deploy not implemented'
            else
              echo 'Skipping deploy for branch: '$CIRCLE_BRANCH
            fi
      # Example usage of environment variables
      # - run:
      #     name: Use environment variables
      #     command: echo $MSAL_CLIENT_ID

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-frontend
      - build-backend
      - test-backend:
          requires:
            - build-backend
      - sonarqube-analysis:
          requires:
            - build-backend
            - test-backend
            - build-frontend
      - deploy:
          requires:
            - sonarqube-analysis
          filters:
            branches:
              ignore: "!^dev$|^main$"
            tags:
              ignore: ["*"]
