name: Node.js CI

on:
 push:
    branches: [ "dev" ]
 pull_request:
    branches: [ "dev" ]

jobs:
 build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['iam-enterprise-architecture-backend', 'iam-enterprise-architecture-frontend']
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: ${{ matrix.directory }}/package-lock.json
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ matrix.directory }}
        
    - name: Build
      run: npm run build --if-present
      working-directory: ${{ matrix.directory }}
        
    - name: Test
      run: npm test
      working-directory: ${{ matrix.directory }}
